
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interface\IOpenApiMediaType.cs" />
    <Compile Remove="Repository\OpenApiMediaTypeFactory.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\libraryInfra\libraryInfra.csproj" />
    <ProjectReference Include="..\libraryModel\libraryModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interface\" />
  </ItemGroup>


</Project>